version: '3'
services:
  minio:
    image: minio/minio
    container_name: minio
    privileged: true
    restart: always
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./minio/data/:/data
      - ./minio/config/:/root/.minio
    command: server --address ":9000" --console-address ":9090" /data
    environment:
        - MINIO_ROOT_USER=admin
        - MINIO_ROOT_PASSWORD=password
  debezium:
    image: datafuselabs/databend
    ports:
      - "8000:8000"
      - "3307:3307"
    volumes:
      - ./databend/meta_storage_dir:/var/lib/databend/meta
      - ./databend/query_storage_dir:/var/lib/databend/query
      - ./databend/log_dir:/var/log/databend
    environment:
      QUERY_DEFAULT_USER: databend
      QUERY_DEFAULT_PASSWORD: databend
      QUERY_STORAGE_TYPE: s3
      AWS_S3_ENDPOINT: minio:9000
      AWS_S3_BUCKET: databend
      AWS_ACCESS_KEY_ID: ROOTUSER
      AWS_SECRET_ACCESS_KEY: CHANGEME123